# Generated by Django 5.1.4 on 2025-01-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
